aws:
  platform_type: "HPC" #change to GDNA or HPC
  GDNA:
    s3:
      bucket_name: "gilead-edp-research-dev-us-west-2-pubmed"
      bucket_region: "us-west-2"
  HPC:
    s3:
      bucket_name: "gilead-ri-hpc-pubmed-dev-us-west-2"
      bucket_region: "us-west-2"
