golden_dataset_article_ids:
  - "2361529"
  - "8325052"
  - "5093171"
  - "3251891"
  - "5450131"
  - "6519061"
  - "7160534"
  - "6947812"
  - "4154841"
  - "4317915"
  - "5642389"
  - "3504940"
  - "5384703"
  - "7671072"
  - "8057655"
  - "2538758"
  - "7932977"
  - "4856585"
  - "5403387"
  - "7327149"
  - "7575440"
  - "6642800"
  - "5724586"
  - "5087704"
  - "6202580"
  - "5482138"
  - "5870096"
  - "4869765"
  - "5988498"
  - "4856797"
  - "4453850"
  - "6362936"
  - "3424666"
  - "6202542"
  - "5868625"
  - "6248272"
  - "3756101"
  - "5355363"
  - "4970829"
  - "6691185"
  - "7584802"
  - "4850750"
  - "6358562"
  - "7371756"
  - "3940863"
  - "6367552"
  - "4999419"
  - "5231907"
  - "4212561"
  - "6579872"
  - "8111265"
  - "6432898"
  - "7807832"
  - "5489751"
  - "4160987"
  - "5125076"
  - "4829131"
  - "3469846"
  - "6521762"
  - "6065473"
  - "4725461"
  - "6064590"
  - "6658608"
  - "5558684"
  - "6924325"
  - "8312512"
  - "8137272"
  - "6163012"
  - "7937841"
  - "4244293"
  - "8315452"
  - "6303615"
  - "7102881"
  - "4273004"
  - "5483497"
  - "3443515"
  - "6977168"
  - "6956603"
  - "6064582"
  - "7366789"
  - "5320748"
  - "5561797"
  - "4541544"
  - "7787955"
  - "5736065"
  - "5304989"
  - "4176452"
  - "7920504"
  - "3563999"
  - "3913798"
  - "7955951"
  - "6781612"
  - "5599204"
  - "7536739"
  - "7952801"
  - "7540442"
  - "6468187"
  - "4439943"
  - "8202655"
  - "7293078"
  - "7160558"
  - "7548235"
  - "3672380"
  - "7541005"
  - "2694329"
  - "4488608"
  - "7989961"
  - "4606373"
  - "2528145"
  - "4632175"
  - "7982715"
  - "7894017"
  - "3275680"
  - "7491043"
  - "7185216"
  - "3908495"
  - "4904963"
  - "2905299"
  - "5772929"
  - "7583132"
  - "4939985"
  - "7453501"
  - "7321680"
  - "5835892"
  - "8334352"
  - "4286153"
  - "6773970"
  - "7046517"
  - "6463461"
  - "2480972"
  - "7734496"
  - "3571730"
  - "5035793"
  - "8132202"
  - "4580380"

enhanced_golden_dataset_article_ids:
  - "10923916"
  - "10915134"
  - "8748704"
  - "10831337"
  - "9413286"
  - "10698546"
  - "11245995"
  - "11116757"
  - "9896310"
  - "10870877"
  - "10645594"
  - "10017705"
  - "10897627"
  - "10370087"
  - "8418271"
  - "11231252"
  - "11118283"
  - "10907391"
  - "10232659"
  - "10912034"
  - "10443631"
  - "11371094"
  - "9161072"
  - "11014662"
  - "8579308"
  - "10619435"
  - "9746914"
  - "10117631"
  - "9050543"
  - "11008188"
  - "11073880"
  - "11387199"
  - "9674284"
  - "11405273"
  - "11208295"
  - "11319832"
  - "10837166"

litqa_dataset_article_ids:
  - "10917522"
  - "10871260"
  - "10024153"
  - "10897447"
  - "10530073"
  - "10773119"
  - "11078116"
  - "11009116"
  - "10888836"
  - "10764289"
  - "8995031"
  - "10990113"
  - "10830414"
  - "6919571"
  - "10539709"
  - "9350683"
  - "11077751"
  - "9281392"
  - "10954967"
  - "8809391"
  - "10359266"
  - "11067025"
  - "11111400"
  - "11100620"
  - "11062927"
  - "9945969"
  - "11009413"
  - "11078759"
  - "10264397"
  - "11077091"
  - "11113265"
  - "11077085"
  - "11237425"
  - "11077093"
  - "9452294"
  - "11062931"
  - "9746304"
  - "10322706"
  - "11101474"
  - "11077092"
  - "10636190"
  - "10618286"
  - "11107001"
  - "10760936"
  - "9563306"
  - "10987551"
  - "10869271"
  - "9918738"
  - "10942590"
  - "10765522"
  - "11014256"
  - "9797404"
  - "9949159"
  - "11066985"
  - "10491752"
  - "10409721"
  - "7649238"
  - "11101664"
  - "10862896"
  - "11041701"
  - "10393267"
  - "11326130"
  - "10855626"
  - "11062907"
  - "11077059"
  - "11077071"
  - "10983909"
  - "11098102"
  - "10944506"
  - "11194073"
  - "10912769"
  - "11077075"
  - "10131484"
  - "11077077"
  - "10789797"
  - "9729108"
  - "11188114"
  - "10870475"
  - "10927504"
  - "10083194"
  - "10473641"
  - "10916875"
  - "7614541"
  - "11573686"
  - "11021478"
  - "10988632"
  - "9605863"
  - "8584034"
  - "9130329"
  - "9438555"
  - "10730565"
  - "10686827"
  - "11111397"
  - "10261898"
  - "9021019"
  - "9970000"
  - "10719092"
  - "11136670"
  - "10439884"

poc_dataset_article_ids:
  - "7614604"
  - "10163802"
  - "9098652"
  - "10452697"
  - "10213952"
