golden_dataset_article_ids:
 - "10917522"
 - "2361529"
 - "8325052"
 - "10871260"
 - "10024153"
 - "5093171"
 - "3251891"
 - "10923916"
 - "5450131"
 - "6519061"
 - "7160534"
 - "6947812"
 - "4154841"
 - "10897447"
 - "4317915"
 - "5642389"
 - "3504940"
 - "10530073"
 - "5384703"
 - "10915134"
 - "10773119"
 - "11078116"
 - "11009116"
 - "8748704"
 - "7671072"
 - "10888836"
 - "8057655"
 - "2538758"
 - "10831337"
 - "7932977"
 - "10764289"
 - "4856585"
 - "5403387"
 - "7327149"
 - "7575440"
 - "6642800"
 - "5724586"
 - "5087704"
 - "6202580"
 - "5482138"
 - "8995031"
 - "9413286"
 - "10990113"
 - "5870096"
 - "10830414"
 - "4869765"
 - "7614604"
 - "5988498"
 - "10698546"
 - "4856797"
 - "4453850"
 - "6919571"
 - "10539709"
 - "6362936"
 - "9350683"
 - "11077751"
 - "3424666"
 - "6202542"
 - "11245995"
 - "10163802"
 - "5868625"
 - "9281392"
 - "10954967"
 - "6248272"
 - "8809391"
 - "11116757"
 - "3756101"
 - "9098652"
 - "10359266"
 - "11067025"
 - "5355363"
 - "4970829"
 - "11111400"
 - "6691185"
 - "9896310"
 - "7584802"
 - "4850750"
 - "6358562"
 - "11100620"
 - "11062927"
 - "9945969"
 - "7371756"
 - "3940863"
 - "6367552"
 - "11009413"
 - "4999419"
 - "11078759"
 - "5231907"
 - "4212561"
 - "6579872"
 - "10452697"
 - "8111265"
 - "10264397"
 - "6432898"
 - "11077091"
 - "11113265"
 - "11077085"
 - "11237425"
 - "7807832"
 - "11077093"
 - "5489751"
 - "4160987"
 - "9452294"
 - "5125076"
 - "10870877"
 - "10645594"
 - "4829131"
 - "3469846"
 - "6521762"
 - "6065473"
 - "4725461"
 - "6064590"
 - "11062931"
 - "9746304"
 - "10322706"
 - "10017705"
 - "6658608"
 - "11101474"
 - "10897627"
 - "5558684"
 - "11077092"
 - "6924325"
 - "10636190"
 - "10618286"
 - "8312512"
 - "11107001"
 - "8137272"
 - "10760936"
 - "10370087"
 - "6163012"
 - "9563306"
 - "7937841"
 - "4244293"
 - "8315452"
 - "10987551"
 - "10869271"
 - "9918738"
 - "8418271"
 - "10942590"
 - "10765522"
 - "11014256"
 - "9797404"
 - "6303615"
 - "7102881"
 - "11231252"
 - "4273004"
 - "5483497"
 - "3443515"
 - "6977168"
 - "9949159"
 - "11066985"
 - "11118283"
 - "6956603"
 - "6064582"
 - "10491752"
 - "10907391"
 - "10409721"
 - "7649238"
 - "7366789"
 - "5320748"
 - "11101664"
 - "10232659"
 - "5561797"
 - "10862896"
 - "4541544"
 - "11041701"
 - "10393267"
 - "10912034"
 - "7787955"
 - "11326130"
 - "10443631"
 - "5736065"
 - "10855626"
 - "5304989"
 - "11062907"
 - "6946810"
 - "4176452"
 - "7920504"
 - "11077059"
 - "11077071"
 - "3563999"
 - "11371094"
 - "3913798"
 - "10983909"
 - "7955951"
 - "9161072"
 - "11098102"
 - "11014662"
 - "6781612"
 - "5599204"
 - "7536739"
 - "7952801"
 - "7540442"
 - "8579308"
 - "6468187"
 - "10944506"
 - "4439943"
 - "8202655"
 - "7293078"
 - "11194073"
 - "10912769"
 - "7160558"
 - "11077075"
 - "7548235"
 - "3672380"
 - "10131484"
 - "11077077"
 - "10619435"
 - "7541005"
 - "10789797"
 - "9729108"
 - "11188114"
 - "10870475"
 - "10927504"
 - "2694329"
 - "10083194"
 - "4488608"
 - "10473641"
 - "9746914"
 - "10916875"
 - "7989961"
 - "7614541"
 - "4606373"
 - "10117631"
 - "2528145"
 - "9050543"
 - "4632175"
 - "11573686"
 - "11021478"
 - "7982715"
 - "10988632"
 - "9605863"
 - "8584034"
 - "9130329"
 - "7894017"
 - "9438555"
 - "10730565"
 - "11008188"
 - "3275680"
 - "10686827"
 - "11111397"
 - "7491043"
 - "7185216"
 - "10261898"
 - "11073880"
 - "3908495"
 - "4904963"
 - "2905299"
 - "9021019"
 - "11387199"
 - "5772929"
 - "7583132"
 - "4939985"
 - "9674284"
 - "7453501"
 - "7321680"
 - "5835892"
 - "8334352"
 - "4286153"
 - "9970000"
 - "10719092"
 - "11136670"
 - "6773970"
 - "10213952"
 - "11405273"
 - "10439884"
 - "11208295"
 - "10495415"
 - "7046517"
 - "6463461"
 - "2480972"
 - "10312723"
 - "7734496"
 - "10748745"
 - "3571730"
 - "11319832"
 - "9833661"
 - "5035793"
 - "10387117"
 - "9683785"
 - "8132202"
 - "4580380"
 - "10837166"

thalidomide_articles_ids:
  - "2212313"
  - "2943476"
  - "4737249"
  - "4853910"
  - "5778013"
  - "6120908"
  - "6156078"
  - "7487777"
  - "7795537"
