xml_to_html_template_path: "xml_to_html_conversion/xml_to_html_template.html"
storage:
  type: "local"  # "local" for HPC or "s3" for S3
  local:
    jit_ingestion_path: "/scratch/pubtator/data/staging/jit_ingestion"
    pmc_path: "/scratch/pubtator/data/staging/pmc_xml"
    bioc_path: "/scratch/pubtator/data/staging/bioc_xml"
    metadata_path: "/scratch/pubtator/data/articles_metadata/metadata"
    aioner_path: "/scratch/pubtator/data/ner_processed/aioner_annotated"
    gnorm2_path: "/scratch/pubtator/data/ner_processed/gnorm2_annotated"
    nlmchem_path: "/scratch/pubtator/data/ner_processed/nlmchem_annotated"
    taggerone_cellLine_path: "/scratch/pubtator/data/ner_processed/taggerone_cellLine_annotated"
    taggerone_disease_path: "/scratch/pubtator/data/ner_processed/taggerone_disease_annotated"
    tmvar_path: "/scratch/pubtator/data/ner_processed/tmvar_annotated"
    annotations_merged_path: "/scratch/pubtator/data/ner_processed/all_in_one_annotated"
    summary_path: "/scratch/pubtator/data/articles_metadata/summary"
    chunks_path: "/scratch/pubtator/data/indexing/chunks"
    embeddings_path: "/scratch/pubtator/data/indexing/embeddings"
    embeddings_archived_path: "data/indexing/archived_embeddings"
    static_html_path: "/scratch/pubtator/data/processed/bioc_html"
    internal_docs_path: "/scratch/pubtator/data/staging/internal_docs"
    internal_docs_html_path: "/scratch/pubtator/data/staging/internal_docs_html"
  s3:
    jit_ingestion_path: "data/staging/jit_ingestion"
    pmc_path: "data/staging/pmc_xml"
    bioc_path: "data/staging/bioc_xml"
    metadata_path: "data/articles_metadata/metadata"
    aioner_path: "data/ner_processed/aioner_annotated"
    gnorm2_path: "data/ner_processed/gnorm2_annotated"
    nlmchem_path: "data/ner_processed/nlmchem_annotated"
    taggerone_cellLine_path: "data/ner_processed/taggerone_cellLine_annotated"
    taggerone_disease_path: "data/ner_processed/taggerone_disease_annotated"
    tmvar_path: "data/ner_processed/tmvar_annotated"
    annotations_merged_path: "data/ner_processed/all_in_one_annotated"
    summary_path: "data/articles_metadata/summary"
    chunks_path: "data/indexing/chunks"
    embeddings_path: "data/indexing/embeddings"
    embeddings_archived_path: "data/indexing/archived_embeddings"
    static_html_path: "data/processed/bioc_html"
    internal_docs_path: "data/staging/internal_docs"
    internal_docs_html_path: "data/staging/internal_docs_html"
workdir:
  base_path: "/code"
model:
  embeddings_model:
    pubmedbert:
      model_path: "/scratch/pubtator/models/pubmedbert-base-embeddings"
      token_limit: 512
    chemberta:
      model_path: "/scratch/pubtator/models/chemberta-77m-mlm"
      token_limit: 512
  summarization_model:
    model_1:
      model_path: "/scratch/pubtator/models/summarization-model"
