storage:
  type: "local"  # Change to "s3" for S3
  local:
    pmc_path: "../../data/staging/pmc_xml"
    bioc_path: "../../data/staging/bioc_xml"
    metadata_path: "../../data/articles_metadata/metadata"
    aioner_path: "../../data/ner_processed/aioner_annotated"
    gnorm2_path: "../../data/ner_processed/gnorm2_annotated"
    nlmchem_path: "../../data/ner_processed/nlmchem_annotated"
    taggerone_cellLine_path: "../../data/ner_processed/taggerone_cellLine_annotated"
    taggerone_disease_path: "../../data/ner_processed/taggerone_disease_annotated"
    tmvar_path: "../../data/ner_processed/tmvar_annotated"
    annotations_merged_path: "../../data/ner_processed/all_in_one_annotated"
    summary_path: "../../data/articles_metadata/summary"
    chunks_path: "../../data/indexing/chunks_test"
    embeddings_path: "../../data/indexing/embeddings"
  s3:
    pmc_path: "data/staging/pmc_xml"
    bioc_path: "data/staging/bioc_xml"
    metadata_path: "data/articles_metadata/metadata"
    aioner_path: "data/ner_processed/aioner_annotated"
    gnorm2_path: "data/ner_processed/gnorm2_annotated"
    nlmchem_path: "data/ner_processed/nlmchem_annotated"
    taggerone_cellLine_path: "data/ner_processed/taggerone_cellLine_annotated"
    taggerone_disease_path: "data/ner_processed/taggerone_disease_annotated"
    tmvar_path: "data/ner_processed/tmvar_annotated"
    annotations_merged_path: "data/ner_processed/all_in_one_annotated"
    summary_path: "data/articles_metadata/summary"
    chunks_path: "data/indexing/chunks"
    embeddings_path: "data/indexing/embeddings"
