storage:
  type: "local"  # Change to "s3" for S3
  local:
    pmc_path: "../../data/staging/thalidomide_full_pmc_xml"
    bioc_path: "../../data/staging/thalidomide_full_bioc_xml"
    metadata_path: "../../data/articles_metadata/thalidomide_metadata"
    aioner_path: "../../data/ner_processed/aioner_annotated"
    gnorm2_path: "../../data/ner_processed/gnorm2_annotated"
    nlmchem_path: "../../data/ner_processed/nlmchem_annotated"
    taggerone_cellLine_path: "../../data/ner_processed/taggerone_cellLine_annotated"
    taggerone_disease_path: "../../data/ner_processed/taggerone_disease_annotated"
    tmvar_path: "../../data/ner_processed/tmvar_annotated"
    annotations_merged_path: "../../data/ner_processed/all_in_one_annotated"
    summary_path: "../../data/articles_metadata/summary"
    chunks_path: "../../data/indexing/chunks"
    embeddings_path: "../../data/indexing/embeddings"
  s3:
    pmc_path: "data/staging/pmc_xml"
    bioc_path: "data/staging/bioc_xml"
    metadata_path: "data/articles_metadata/metadata"
    aioner_path: "data/ner_processed/aioner_annotated"
    gnorm2_path: "data/ner_processed/gnorm2_annotated"
    nlmchem_path: "data/ner_processed/nlmchem_annotated"
    taggerone_cellLine_path: "data/ner_processed/taggerone_cellLine_annotated"
    taggerone_disease_path: "data/ner_processed/taggerone_disease_annotated"
    tmvar_path: "data/ner_processed/tmvar_annotated"
    annotations_merged_path: "data/ner_processed/all_in_one_annotated"
    summary_path: "data/articles_metadata/summary"
    chunks_path: "data/indexing/chunks"
    embeddings_path: "data/indexing/embeddings"
model:
  embeddings_model:
    base_location: "jfrog_artifactory" # Change to "hugging_face" for Hugging Face
    pubmedbert:
      jfrog_artifactory:
        model_path: "../../../models/pubmedbert-base-embeddings/ba210f40b1b6d555d675c2d1ed6372e44570fc3c"
      hugging_face:
        model_path: "NeuML/pubmedbert-base-embeddings"
      token_limit: 512
    biobert:
      jfrog_artifactory:
        model_path: "../../../models/biobert-base-embeddings/1e1b4b3b1b6d555d675c2d1ed6372e44570fc3c"
      hugging_face:
        model_path: "dmis-lab/biobert-v1.1"
      token_limit: 512
    longformer:
      jfrog_artifactory:
        model_path: "../../../models/biobert-base-embeddings/1e1b4b3b1b6d555d675c2d1ed6372e44570fc3c"
      hugging_face:
        model_path: "allenai/longformer-base-4096"
      token_limit: 4096
    medembed:
      jfrog_artifactory:
        model_path: "../../../models/biobert-base-embeddings/1e1b4b3b1b6d555d675c2d1ed6372e44570fc3c"
      hugging_face:
        model_path: "abhinand/MedEmbed-base-v0.1"
      token_limit: 512
    microsoft_biomednlp_biomedbert:
      jfrog_artifactory:
        model_path: "../../../models/biobert-base-embeddings/1e1b4b3b1b6d555d675c2d1ed6372e44570fc3c"
      hugging_face:
        model_path: "microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract-fulltext"
      token_limit: 512
