qdrant:
  url: "http://localhost:6333"
  collections:
      processed_medembed:
        collection_name: "medembed_processed_articles"
        vector_size: 768
        distance_metric: "COSINE"
      processed_pubmedbert:
        collection_name: "pubmedbert_processed_articles"
        vector_size: 768
        distance_metric: "COSINE"
      metadata:
        collection_name: "articles_metadata"
        vector_size: 768
        distance_metric: "COSINE"
      baseline:
        collection_name: "baseline_articles"
        vector_size: 768
        distance_metric: "COSINE"
      test:
        collection_name: "test_collection"
        vector_size: 768
        distance_metric: "COSINE"
