qdrant:
  host: localhost
  port: 6333
  collections:
    annotation_aware:
      inline:
        bioformer:
          collection_name: "annotation_aware_inline_bioformer"
          vector_size: 1536
          distance_metric: "COSINE"
        pubmedbert:
          collection_name: "annotation_aware_inline_pubmedbert"
          vector_size: 1536
          distance_metric: "COSINE"
      append:
        bioformer:
          collection_name: "annotation_aware_append_bioformer"
          vector_size: 1536
          distance_metric: "COSINE"
        pubmedbert:
          collection_name: "annotation_aware_append_pubmedbert"
          vector_size: 1536
          distance_metric: "COSINE"
      full_text:
        bioformer:
          collection_name: "annotation_aware_full_text_bioformer"
          vector_size: 1536
          distance_metric: "COSINE"
        pubmedbert:
          collection_name: "annotation_aware_full_text_pubmedbert"
          vector_size: 1536
          distance_metric: "COSINE"
    grouped_annotation_aware_sliding_window:
      inline:
        bioformer:
          collection_name: "grouped_annotation_aware_sliding_window_inline_bioformer"
          vector_size: 1536
          distance_metric: "COSINE"
        pubmedbert:
          collection_name: "grouped_annotation_aware_sliding_window_inline_pubmedbert"
          vector_size: 1536
          distance_metric: "COSINE"
      append:
        bioformer:
          collection_name: "grouped_annotation_aware_sliding_window_append_bioformer"
          vector_size: 1536
          distance_metric: "COSINE"
        pubmedbert:
          collection_name: "grouped_annotation_aware_sliding_window_append_pubmedbert"
          vector_size: 1536
          distance_metric: "COSINE"
      full_text:
        bioformer:
          collection_name: "grouped_annotation_aware_sliding_window_full_text_bioformer"
          vector_size: 1536
          distance_metric: "COSINE"
        pubmedbert:
          collection_name: "grouped_annotation_aware_sliding_window_full_text_pubmedbert"
          vector_size: 1536
          distance_metric: "COSINE"
    passage:
      inline:
        bioformer:
          collection_name: "passage_inline_bioformer"
          vector_size: 1536
          distance_metric: "COSINE"
        pubmedbert:
          collection_name: "passage_inline_pubmedbert"
          vector_size: 1536
          distance_metric: "COSINE"
      append:
        bioformer:
          collection_name: "passage_append_bioformer"
          vector_size: 1536
          distance_metric: "COSINE"
        pubmedbert:
          collection_name: "passage_append_pubmedbert"
          vector_size: 1536
          distance_metric: "COSINE"
      full_text:
        bioformer:
          collection_name: "passage_full_text_bioformer"
          vector_size: 1536
          distance_metric: "COSINE"
        pubmedbert:
          collection_name: "passage_full_text_pubmedbert"
          vector_size: 1536
          distance_metric: "COSINE"
    sliding_window:
      inline:
        bioformer:
          collection_name: "sliding_window_inline_bioformer"
          vector_size: 1536
          distance_metric: "COSINE"
        pubmedbert:
          collection_name: "sliding_window_inline_pubmedbert"
          vector_size: 1536
          distance_metric: "COSINE"
      append:
        bioformer:
          collection_name: "sliding_window_append_bioformer"
          vector_size: 1536
          distance_metric: "COSINE"
        pubmedbert:
          collection_name: "sliding_window_inline_pubmedbert"
          vector_size: 1536
          distance_metric: "COSINE"
      full_text:
        bioformer:
          collection_name: "sliding_window_full_text_bioformer"
          vector_size: 1536
          distance_metric: "COSINE"
        pubmedbert:
          collection_name: "sliding_window_inline_pubmedbert"
          vector_size: 1536
          distance_metric: "COSINE"
