qdrant:
  host: localhost
  port: 6333
  collections:
      processed_medembed:
        collection_name: "articles_sliding_window_prepend_bioformer_medembed"
        vector_size: 768
        distance_metric: "COSINE"
      processed_pubmedbert:
        collection_name: "articles_sliding_window_prepend_bioformer_pubmedbert"
        vector_size: 768
        distance_metric: "COSINE"
      metadata:
        collection_name: "articles_metadata"
        vector_size: 768
        distance_metric: "COSINE"
      baseline:
        collection_name: "baseline_articles"
        vector_size: 768
        distance_metric: "COSINE"
      test:
        collection_name: "test_collection"
        vector_size: 768
        distance_metric: "COSINE"
