vector_db:
  type: "opensearch"  # Change to "qdrant" for qdrant
  qdrant:
    vector_db_params:
        url: "http://localhost:6333"
    index_params:
        processed_medembed:
          collection_name: "medembed_processed_articles"
          vector_size: 768
          distance_metric: "COSINE"
        processed_pubmedbert:
          collection_name: "pubmedbert_processed_articles"
          vector_size: 768
          distance_metric: "COSINE"
        metadata:
          collection_name: "articles_metadata"
          vector_size: 768
          distance_metric: "COSINE"
        baseline:
          collection_name: "baseline_articles"
          vector_size: 768
          distance_metric: "COSINE"
        test:
          collection_name: "test_collection"
          vector_size: 768
          distance_metric: "COSINE"
  qdrant_cloud:
    vector_db_params:
        url: "https://5e4c7f7a-0b0c-46fb-a8a4-0e8229cbaa76.eu-west-2-0.aws.cloud.qdrant.io:6333"
    index_params:
        processed_pubmedbert:
          collection_name: "pubmedbert_processed_articles"
          vector_size: 768
          distance_metric: "COSINE"
        metadata:
          collection_name: "articles_metadata"
          vector_size: 768
          distance_metric: "COSINE"
        baseline:
          collection_name: "baseline_articles"
          vector_size: 768
          distance_metric: "COSINE"
        test:
          collection_name: "test_collection"
          vector_size: 768
          distance_metric: "COSINE"
  opensearch:
    vector_db_params:
      host: "localhost"
      port: 9200
    index_params:
        processed_pubmedbert:
          index_name: "pubmedbert_processed_articles"
          vector_size: 768
          space_type: "cosinesimil"
          engine: "lucene"
          method: "hnsw"
        test:
          index_name: "test_index"
          vector_size: 768
          space_type: "cosinesimil"
          engine: "lucene"
          method: "hnsw"
  opensearch_cloud:
    vector_db_params:
      host: "https://vpc-research-dev-domain-a7dj35akdal35go3cv5eitd5ba.us-west-2.es.amazonaws.com"
      verify_certs: "True"
      region: "us-west-2"
      service: "es"
    index_params:
      processed_pubmedbert:
        index_name: "pubmed__grai_opensearch"
        vector_size: 768
        space_type: "cosinesimil"
        engine: "lucene"
        method: "hnsw"
